### PR TITLE
Cleanups in Listings.go

### PR DESCRIPTION
**Pull request by JustinDrake**
Includes changing `Desc` to `Description` for consistency. This may require an equivalent change on the frontend.

### CODE REVIEW

**Comment by cpacia** [comment]
Just have to let @rmisio know that `desc` was changed to `description` in the listing index.

**Comment by rmisio** [comment]
> Just have to let @rmisio know that desc was changed to description in the listing index.

Who do you think you are!?

<sup>(just kidding, sounds good :))</sub>

**Comment by cpacia** [comment]
Also @JustinDrake do you want to update api.yaml to reflect the change from `desc` to `description`.

**Comment by cpacia** [comment]
Actually looks like that api call isn't in the yaml and needs to be created.

**Pull request merged**
