### PR TITLE
Adding Travis and Go report card badges to README

### PR DESCRIPTION
**Pull request by mtlynch**

### CODE REVIEW

**Comment by hoffmabc** [comment]
I will be adding a Travis script proper soon.

**Comment by mtlynch** [comment]
>I will be adding a Travis script proper soon.

Is this PR blocked on those changes? The badges will work regardless. Would you prefer I took out the Travis badge and only added the report card in this PR?

**Comment by cpacia** [comment]
If you want to rebase this I will merge it. Also good project if someone wants to tackle all the gofmt and golint stuff.

**Comment by hoffmabc** [comment]
I'm working on that @cpacia

**Comment by mtlynch** [comment]
Rebased and ready

**Pull request merged**
