### PR TITLE
[#1681] Protect POSTReleaseEscrow sweep when there are no inputs

### LINKED ISSUE #1681: Order in FULFILLED state with no funds pending cannot completed by vendor
In the scenario that a vendor has an order that is in a FULFILLED state but the inputs to the payment address have already been spent (unsure of how this state was achieved), the vendor gets a 400 Bad Request from the wallet API due to have no inputs for sweeping.

We want to bypass the Sweep attempt if all inputs are spent to allow the order to progress to PROCESSING_ERROR with text associated indicating that there are no inputs to process to FINALIZE_PAYMENT.

### PR DESCRIPTION
**Pull request by hoffmabc**
This issue fixes the scenario where the BUYER released the funds but the SELLER did not receive the completion message (but likely did receive the coins).

### CODE REVIEW

**Comment by szollo** [comment]
Can one of the admins verify this patch?

**Comment by hoffmabc** [comment]
Is this worth putting into 0.13.8 @placer14 ?

**Comment by placer14** [comment]
@hoffmabc This is worth considering. Is there a reproduceable test scenario we can do before/after this patch to ensure we're making a useful change?

**Comment by hoffmabc** [comment]
It's been reported in the wild, but I'm not sure of a reproducible scenario. I will see if I can replicate it on my side.

**Comment by hoffmabc** [comment]
Ready for review @placer14

**Pull request merged**
