### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by cpacia** [comment]
Looks like just a merge conflict needs to be fixed then it can be merged.

**Comment by hugovk** [comment]
Resolved!

**Comment by placer14** [comment]
@hugovk , would you mind reaching out to us in slack or via email? We'd like to send a small token of appreciation but aren't sure where to send it. You can find my [email here](https://gist.github.com/placer14/b7bb0c3c0510af1cfda3c474cc923a3a).

**Comment by hugovk** [comment]
@placer14 Emailed, thanks!

**Pull request merged**
