### PR TITLE
SMTP (and other) notifications mechanism

### PR DESCRIPTION
**Pull request by yurizhykin**
Attempt to abstract out notification mechanism into separate part of the service. This PR is currently just for progress tracking purpose. Most commits will be squashed/changed later. Hope to receive comments when it's more or less ready. 

*Update*: Spent some time trying to change as little as possible, but it seems that notifications do need some refactoring (for example interface for integration of dangling `notifications.Notification` type). So started from that.

Task list (checked ones are ready for review):
- [x] Unify notifications in `core`, `listener` and `service` packages
- [x] Implement notifier mechanism
- [x] Implement SMTP notifier
- [x] Implement header/body generator for notifications
- [x] ~~Notification interface type~~ seems unnecessary
- [x] Testing

### CODE REVIEW

**Comment by yurizhykin** [comment]
Spent some time trying to change as little as possible, but it seems that notifications do need some refactoring (for example interface for integration of dangling `notifications.Notification` type). So started from that.

**Comment by hoffmabc** [comment]
@yurizhykin can we resolve the conflicts so we can move forwarrd on this? ping @cpacia

**Comment by yurizhykin** [comment]
@hoffmabc , sure. Just rebased on 'master'. Can be merged now, and I will add tests in another PR. But I think, review would be useful, since my commits change some core parts.

**Comment by hoffmabc** [comment]
Yes of course. Thank you for the rebase.

**Comment by yurizhykin** [comment]
Final touch: added template for notification emails. Also added `ServerPort` field to `SMTPSettings` struct, as most popular services seem to break "port 25" convention. Tested in [`MailHog`](https://github.com/mailhog/MailHog), everything seems alright. 

QA test is not done yet: spent whole evening trying to read from *python*'s `subprocess.Popen.stdout` on `smtpd.DebuggingServer` and failed. In REPL I observe that first `read()` blocks indefinitely, and when it is interrupted from keyboard, subsequent one actually returns expected data. Have no idea what it is. Have anyone seen something like that before?

Anyway, QA test can be rewritten to use `MailHog` and its JSON API but it seems like a lot of overhead to me.

**Comment by cpacia** [comment]
Looks pretty good to me. Would just probably remove the `status` from the describe switch. 

Other than that I just need to test locally.

**Pull request merged**
