### PR TITLE
follow symlink to onion_key

### PR DESCRIPTION
**Pull request by pinheadmz**
fixes https://github.com/OpenBazaar/openbazaar-go/issues/826

I suspect this change may be helpful elsewhere in the code base where `filepath.Abs` is used. I do not know if there is any drawback to switching them all to `filepath.EvalSymlinks`.

### CODE REVIEW

**Comment by pinheadmz** [comment]
@cpacia any love for this bug fix before the next release?

**Comment by cpacia** [comment]
Let me take another look. Thanks for reminding me.

**Comment by jjeffryes** [comment]
@cpacia @placer14 @tyler-smith can this be reviewed?

**Comment by placer14** [comment]
Closing so we can properly vendor the change.

**Comment by pinheadmz** [comment]
Thanks guys!

**Pull request closed without merging**
