### PR TITLE
refactor images.go and adjust sizes (see issue #349)

### PR DESCRIPTION
**Pull request by JustinDrake**
Note this is untested (hoping for the regression test suite and CI to catch any bugs).

### CODE REVIEW

**Comment by hoffmabc** [comment]
We're going to need the untested stuff obviously to get fixed or CI will continue to fail.

**Comment by JustinDrake** [comment]
Apologies for the gofmt issue (my Sublime plugin suddenly stopped working). It's now fixed.

**Comment by JustinDrake** [comment]
Regarding getting rid of the 60x60 product image, this was the suggestion of @jjeffryes (upvoted by  @morebrownies) in https://github.com/OpenBazaar/openbazaar-go/issues/349. I also think it's fine :)

**Comment by cpacia** [comment]
Looks like jsonapi_test is failing with the change in hashes. I think it's the avatar header and profile tests.

**Pull request merged**
