### PR TITLE
(#1420, #1936) Eth txn notification over websockets

### LINKED ISSUE #1420: Socket notifications for ETH transactions don't appear to be working
I didn't see any notifications arrive over the socket for ETH transactions in the wallet. The only way to see new transactions in the desktop client was to reload the client so the transactions would be obtained from a GET call.

### LINKED ISSUE #1783: Improve ETH Spend to sync return more quickly or to become entirely async
As a stopgap, we have allowed the ETH Spend method to take as long as 3 minutes waiting for the transaction to be mined by the network as there is no other way to ensure whether the transaction is successful or not until then. We would either improve this to emit a websocket message result for ETH transactions which would allow the Spend request to return the client response more quickly while still tracking the result of the Spend.

This improvement should be discussed with desktop and mobile client integration teams.

### PR DESCRIPTION
**Pull request by amangale**
This PR will:

1. Enable subscribers (desktop/haven) to listen to incoming eth transactions for the wallet (closes #1420) 
2. Make the ethereum wallet use the Tor proxy (closes #1951)
3. Handle async API request to close #1783

### CODE REVIEW

**Comment by amangale** [comment]
I am getting this error on the ETH QA test which I would like to resolve before this PR is reviewed.
```
$ python3 eth_dispute_close_split.py -b ../openbazaar-qa  -c "ETH"
Running EthDisputeCloseSplitTest
2020/01/28 11:22:09 Initializing OpenBazaar node at /tmp/openbazaar-go/0
2020/01/28 11:22:25 
OpenBazaar Server v0.13.8
2020/01/28 11:22:28 Initializing OpenBazaar node at /tmp/openbazaar-go/1
2020/01/28 11:22:54 
OpenBazaar Server v0.13.8
2020/01/28 11:22:59 Initializing OpenBazaar node at /tmp/openbazaar-go/2
2020/01/28 11:23:10 
OpenBazaar Server v0.13.8
2020/01/28 11:23:12 Initializing OpenBazaar node at /tmp/openbazaar-go/3
2020/01/28 11:23:30 
OpenBazaar Server v0.13.8

~~~~~~~~~~~~~~~~~~~~~~ ob.log ~~~~~~~~~~~~~~~~~~~~~~
2020-01-28 11:22:54.209 [DEBUG] [core/CheckAndSetUlimit] Successfully raised file descriptor limit to 32000
2020-01-28 11:22:54.370 [INFO] [cmd/Execute] Peer ID:  QmVQzkdi3Fq6LRFG9UNqDZfSry67weCZV6ZL26QVx64UFy
2020-01-28 11:22:54.370 [INFO] [cmd/printSwarmAddrs] Swarm listening on /ip4/127.0.0.1/tcp/1184
2020-01-28 11:22:55.075 [INFO] [cmd/newHTTPGateway] Gateway/API server listening on /ip4/127.0.0.1/tcp/7621
2020-01-28 11:22:55.075 [INFO] [cmd/func3] Starting multiwallet...
2020-01-28 11:22:55.075 [INFO] [service/New] OpenBazaar service running at /openbazaar/app/1.0.0
2020-01-28 11:22:55.075 [INFO] [cmd/func3] OpenBazaar Service Ready
2020-01-28 11:22:55.079 [DEBUG] [recordAgingNotifier/PerformTask] notifications created/records updated: sales: 0/0, purchaseTimeout: 0/0, purchaseExpire: 0/0, dispute: 0/0
2020-01-28 11:22:56.044 [INFO] [ipfs/Publish] Published Qme2BvpxWE9zFBu9hBAsiN6D1BVZEaJDKBPN3cx8mzps1C to IPNS
2020-01-28 11:24:05.827 [DEBUG] [core/UpdateProfile] settings not set, using default preferred currencies
2020-01-28 11:24:06.788 [INFO] [ipfs/Publish] Published QmeVvwaGdtVSVwGGxWhKUAWRRPZMMK5Z2QFCeo1TNa4Jry to IPNS
2020-01-28 11:24:10.742 [DEBUG] [core/UpdateProfile] settings not set, using default preferred currencies
2020-01-28 11:24:12.877 [INFO] [ipfs/Publish] Published Qmctr5sr2n3onHqSWztrzzgDxxWbG4BWwvtn9PW7gwm6Co to IPNS


TestFailure('EthDisputeCloseSplitTest - FAIL: Purchase POST failed. Reason: %s', 'identity signature on contract failed to verify')
```

**Comment by placer14** [comment]
@amangale This is signing problem which was discovered in PR1906. I've been able to recreate the issue and am attempting to root cause the problem. Let's get the PR delta straightened out (it still only shows changes to the gorilla websocket vendor package and nothing more) in the meantime so it can be ready to merge.

**Comment by amangale** [comment]
@placer14  - Due to some upstream sync or something, all the relevant changes to the eth wallet except for the vendor dependencies have gotten into ethereum-master. I had already pushed changes for both PR 1915 and 1951 to go-ethwallet and maybe that is why the present delta shows only the last cleanup change. hope this clarifies.

**Comment by placer14** [comment]
@amangale After more throughly looking through both PRs together, there's a few things which don't add up about the theory behind PR1915 including the missing changes from this PR. If PR1915 had the changes which complete the issues outlined in the description of this PR, I would have expected to see:
- where the client construction was considering proxy.Dialer. Right now, I only see it applied to the price fetcher.
- where the nonce that was added [here](https://github.com/OpenBazaar/openbazaar-go/pull/1915/files#diff-5f7d9f5ad89197212dbacf0649dd64b2R891) is being consumed (assuming the nonce is some unique ID which enables the async transaction websocket)

I'm also checking out the changes made in `gorilla/websocket` and see we inject a proxy from the environment despite it being manually passed into the price fetcher construction and used there. This inconsistent construction is really confusing from usage point of view and creates a scenario where one proxy could be used for one behavior and another proxy for a different behavior...leading to all sorts of network-inconsistent behavior.

If we were accepting the changes in `gorilla/websocket` as it is, it's not clear which git repo and hash has these changes and appear to only live inside the vendor folder. Were they applied upstream to the owner repo? If so, what SHA hash is it at so I can update the godep.json? If not, how do propose we restore those changes should our vendor folder state need to be rebuilt?

Lastly, do the QA tests accurately prove all of this new behavior? (I realize the signing is broken still, but does the QA example validate the responses are there as needed by the client UI?

**Comment by placer14** [comment]
It also seems we revert to an older version of `gorilla/websocket` at the same time as doing our injection. Are we sure we want to revert the interface changes that were already vendored? (I noticed this because when I check out latest master from that upstream repo, there are a bunch of changes in master that this PR seems to be removing.)

**Comment by amangale** [comment]
The websocket was completely removed as the websocket solution was not meeting the requirements. There should not be any gorilla/websocket dependency as far as go-ethwallet is concerned. If it is still there, it will be cleaned up before merge. This eliminates the need for the proxy.Dialer as well. Some of this cleanup will happen once this PR is going to be merged in the fixed ethereum-master. Please note that multiwallet uses gorilla/websocket so whether gorilla/websocket dependency should or shouldnt be updated is mostly Chris' call.
As for the QA tests, the ethereum tests mirror the existing UTXO tests. If the question is not ethereum specific then Chris would be right person to ask regarding the value/correctness of the current QA tests. AFAIK, the QA tests  do cover a lot of ordering scenarios and the responses are checked for the presence/absence of attributes before passing them. 
One last thing, the existing eth qa tests are all passing on this branch, both with and without Tor.

**Pull request merged**
