### PR TITLE
Clean up listings and ratings indexes; fixes #381

### LINKED ISSUE #381: What happens if a listing has the title "Index"?
If a listing has the title `Index` the slug for it is then `index` and the file name is `index.json` which collides with the main listings `index.json`. Is there code to protect against such name collisions?

### PR DESCRIPTION
**Pull request by JustinDrake**
As per @hoffmabc's request.

### CODE REVIEW

**Comment by cpacia** [comment]
@JustinDrake this is probably better to just put a check on the slug when saving that it cant be named index rather than refactoring the structure of the directory.

**Comment by JustinDrake** [comment]
Why accumulate technical debt in the protocol at this early stage (pre-release)? Separation of concerns in the `listings` and `ratings` folder is clearly superior than the current approach.

**Comment by cpacia** [comment]
I don't know what you mean. Those folders are already separated. This now sticks listing data in two separate folders... the root and the listing folder.

**Comment by JustinDrake** [comment]
I mean that the `listings` folder does precisely one thing, namely store listings.

**Comment by tyler-smith** [comment]
I support the proposal but have not reviewed the PR (it was assigned to Chris so I never checked it out).

@cpacia What do you think? I don't mind reviewing the PR if you'd rather not but do you have a yay or nay on the concept? Or more discussion?

**Comment by cpacia** [comment]
I don't mind revisiting later, but it doesn't seem like an imperative change at this time. We would need a rebase to revisit as well.

**Pull request closed without merging**
