### PR TITLE
Litecoin Support for OpenBazaar

### PR DESCRIPTION
**Pull request by LeehoLim**
Adding LTC wallet for OpenBazaar. Changes include in OpenBazaar/go/bitcoin folder -> created Litecoind folder. Please make the according adjustments necessary in the cmd folder / interface / anywhere else necessary.

### CODE REVIEW

**Comment by hoffmabc** [comment]
Thank you very much for the contribution @LeehoLim.

**Comment by LeehoLim** [comment]
Brian - sorry, I kept superfluous files. Let me go ahead and delete them.

**Comment by LeehoLim** [comment]
Not a problem at all! Let me know if there is anything I can go over.

**Comment by placer14** [comment]
This is great effort. Thank you @LeehoLim. I know you're working on an SPV solution to replace this. Please ensure your contribution is well-tested so we can make sure it's supported over the long term. Going to close this PR as it's not going to be used.

**Pull request closed without merging**
