### PR TITLE
adds test for GetAPIUsernameAndPw function

### PR DESCRIPTION
**Pull request by davalb**
I want to contribute something to the new OpenBazaar server and thought unit tests might be good place to start. I chose the config.go file because I was looking for some simple functions to start with.
Please let me know what needs to be changed and what could be improved! Thanks.

### CODE REVIEW

**Comment by davalb** [comment]
Wow, I wonder why the coverage has decreased so strongly? Is it because I added the repo/testdata/config file? The file is a fixture for testing-purposes. Is there a way to exlude it from the coverage-computation?

**Comment by tyler-smith** [comment]
Hey @davalb, thanks for getting involved! I think you're correct about the test coverage thing. 

@hoffmabc I think you've been setting up coveralls, could you check that out please?

I think making the test config file path a constant would be good so we can reuse it when testing the other config funcs.

```go
import (
	"testing"
)

const testConfigPath = "testdata/config"

func TestGetAPIUsernameAndPw(t *testing.T) {
	username, pw, err := GetAPIUsernameAndPw(testConfigPath)
// etc ...
```

It's great you've started to test the config stuff because I want to change the unchecked type assertions into a Config struct that we unmarshal into. This will make that refactoring easier.

**Comment by hoffmabc** [comment]
I believe it decreased because the coverage tool wasn't calculating the directory code in the total until you added a unit test file.

**Comment by tyler-smith** [comment]
That makes sense. Good to keep in mind.

**Comment by cpacia** [comment]
Thanks @davalb !

**Comment by cpacia** [comment]
It looks like you need to run gofmt for travis to pass. If you have an ide, you can usually set it up to run automatically on save.

**Comment by davalb** [comment]
@tyler-smith thanks! Glad it is useful, I want to write tests for the other funtctions in the config.go file as well. I added the constant to the test-file as you suggested.
@cpacia Just ran gofmt and made changes to the code accordingly.

**Pull request merged**
