### PR TITLE
Fix casing and spacing

### PR DESCRIPTION
**Pull request by duosearch**

### CODE REVIEW

**Comment by cpacia** [comment]
Keep in mind any time you change a proto file you need to re-compile the pb files.
```
protoc --go_out=./ profile.proto
```

This creates a conflict with the other `fileDescriptor`s in the same package so I've been renaming them.

**Comment by duosearch** [comment]
@cpacia Would it make sense to generate the pb files at compile time?

**Comment by AubreyF** [comment]
@duosearch I prefer generating them by hand as necessary, as the resulting Structs can then be inspected by autocompleting IDEs, etc.

**Comment by cpacia** [comment]
I fixed this and update the pb file

**Pull request closed without merging**
