### PR TITLE
(#1846) Unable to load legacy orders due to payment coin refactor

### LINKED ISSUE #1846: Unable to load legacy order
When loading orders produced prior to `etherum-master`, legacy orders are not loadable and cause a server panic as follows:
```
goroutine 16072 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/debug/stack.go:24 +0xb1
runtime/debug.PrintStack()
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP.func1()
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:177 +0x16c
panic(0x5ad4fa0, 0x73f4f70)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/runtime/panic.go:513 +0x1e6
github.com/OpenBazaar/openbazaar-go/core.(*OpenBazaarNode).GetOrder(0xc00141b0e0, 0xc0011ac00e, 0x2e, 0x0, 0x0, 0x0)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/core/order.go:71 +0x4ad
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).GETOrder(0xc00085e600, 0x6373980, 0xc000bb6000, 0xc004741e00)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:1721 +0xc6
github.com/OpenBazaar/openbazaar-go/api.get(0xc00085e600, 0xc00221a380, 0x38, 0x6373980, 0xc000bb6000, 0xc004741e00)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/endpoints.go:165 +0x980
github.com/OpenBazaar/openbazaar-go/api.(*jsonAPIHandler).ServeHTTP(0xc00085e600, 0x6373980, 0xc000bb6000, 0xc004741e00)
        /Users/mg/go/src/github.com/OpenBazaar/openbazaar-go/api/jsonapi.go:184 +0xfda
net/http.(*ServeMux).ServeHTTP(0xc00140d8f0, 0x6373980, 0xc000bb6000, 0xc004741e00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2361 +0x1a4
net/http.serverHandler.ServeHTTP(0xc0013d5860, 0x6373980, 0xc000bb6000, 0xc004741e00)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2741 +0x1e9
net/http.(*conn).serve(0xc0039d48c0, 0x6375580, 0xc002f27140)
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:1847 +0x1146
created by net/http.(*Server).Serve
        /usr/local/Cellar/go@1.11/1.11.6/libexec/src/net/http/server.go:2851 +0x7b0
```

To reproduce:
1. Create any order with a node using daemon v0.13.6 or earlier.
2. Stop the node and restart it using the latest from `ethereum-master` (the above panic was produced with 0145adba7b63758f02f5bc67ab2098f7d34f13f2)
3. Attempt to load the order via the client UI or via `GET /ob/order/:orderID`
4. Observe the panic in the logs with a 200 OK response.

### PR DESCRIPTION
**Pull request by hoffmabc**
I'm sure this is not a long term fix considering there should be a migration of pre-ETH contracts to the new payment refactor, but it does alleviate the panic when loading orders into the UI.

Fixes #1846

### CODE REVIEW

**Comment by cpacia** [comment]
I don't think we can migrate existing orders without breaking the signature :(

**Comment by hoffmabc** [comment]
I think the answer would be to re-sign the contracts wouldn't it @cpacia? Is that difficult?

**Comment by hoffmabc** [comment]
Ok so @placer14 @cpacia what's the move forward here for this one?

**Comment by placer14** [comment]
I haven't looked at it yet. Trying to wrap up my refactoring which I'd like to deliver ASAP. Unless someone else has confidence enough to merge this change, that's my next step.

**Comment by placer14** [comment]
Edit: Updated this PR to convert values from legacy schema into the new v5 fields. But as pointed out, this will make the contract signatures invalid but will make the data operable. A brief discussion suggested that listing signatures are mainly used by the moderator in dispute resolution. While this changeset is outside of the path the moderators take, we may need to apply a similar change there as well.

**Pull request merged**
